version: '3'
services:
  vue:
    build: ./vue-app
    ports:
      - "8080:8080"
    volumes:
      - ./vue-app:/app
  node:
    build: ./node-app
    ports:
      - "3000:3000"
    volumes:
      - ./node-app:/app
