site_name: Squad 04
theme:
  #name: dracula
  name: material
nav:
  - Home: index.md
  - Arquitetura: arquitetura.md
  - Atas:
    - ata-modelo: atas/ata-modelo.md
    - ata-23-03: atas/ata-23-03.md
    
