site_name: Squad 04
theme:
  #name: dracula
  name: material
nav:
  - Home: index.md
  - Ideação: ideacao.md
  - Arquitetura: arquitetura.md
  - Atas:
    - ata-modelo: Atas/ata-modelo.md
    - ata-23-03: Atas/ata-23-03.md
    
